### ISSUE TITLE
Video Call Between Android&iOS Devices

### ISSUE THREAD

**Issue by HakanSAYAR** [twilio/twilio-video-app-ios#106]
Description

Hi, I'm developing a P2P&Group video call application using your SDK. I tested the video call between iOS and Android devices. Only the audio of the Android user comes to the iOS user. The image of the Android user is not displaying to the iOS user. How can I solve this?

**Comment by timrozum** [comment]
Hi @HakanSAYAR,

I would recommend some more testing to narrow down the problem. For example if you try to view the Android participant from another Android device or on the web does the problem still exist? If so it probably is an issue with the Android device supplying the video.

Let me know what you find!

**Comment by HakanSAYAR** [comment]
@timrozum All tests have already been done. iOS & iOS Devices, iOS & Android devices. Tested with different android devices, but the result is the same. We noticed that; we built the [video-quickstart-android](https://github.com/twilio/video-quickstart-android) on android device and [twilio-video-app-ios](https://github.com/twilio/twilio-video-app-ios) on iOS device. The image of the Android user is not displaying to the iOS user. Maybe this detail will help you catch the error.

**Comment by timrozum** [comment]
@HakanSAYAR that helps, I think I understand the problem now. We did not design the video app to be compatible with quickstart apps. However I think I know what may be causing the video problem when you use the different apps together.

I think the video app is expecting the video track name for the camera to be `camera`. And the quickstart could be specifying a different track name or nothing at all in which case a name will be generated. You could look at [this line](https://github.com/twilio/twilio-video-app-ios/blob/1f12902515a4fa12c88ee985554cf3064f729074/VideoApp/VideoApp/Video/Tracks/Core/TrackName.swift#L20) in the video app to see how track name is used. The track names for video app and quickstart will need to be the same in order for it to work.

However I would recommend using the Android video app with the iOS video app. The quickstart code is not as close to production quality as the video app code.
