### ISSUE TITLE
Angular to iOS video rendering.

### ISSUE THREAD

**Issue by Srihari-Talentbridge** [twilio/twilio-video-app-ios#110]
I have an issue rendering video track generated from Angular Twilio code in this iOS demo app. I am using the latest Twilio version and latest code base of this demo app.

Once I connect to the room, audio renders perfectly but not the video ( totally blank ). I have tried with all possibilities of videoCodecs. 

The code works perfectly when rendering video track from Android, React , iOS to iOS. but not from Angular..

Please let me know if I need to provide any other information.

**Comment by timrozum** [comment]
Hi @Srihari-Talentbridge,

I think the problem may be the track name. The iOS is expecting the track name for the camera to be `camera`. I suggest making sure the Angular code is setting the track name to this. You might want to reference `TrackName.swift` in the iOS app. Please let me know if that helps.

**Comment by timrozum** [comment]
Hi @Srihari-Talentbridge, 

I'm going to close this issue but feel free to add more comments if this is still a problem.
