### ISSUE TITLE
How to check if simulcast has been enabled?

### ISSUE THREAD

**Issue by simbara** [twilio/twilio-video-app-ios#112]
Does the statsReport.localVideoTrackStats inside StatsViewController.m contain all the temporal layers of a VP8 Simulcast VideoTrack? The trackCount is always 1.

It looks like there was an issue which was fixed in the javascript sdk (https://github.com/twilio/twilio-video.js/blob/master/CHANGELOG.md#272-august-12-2020)

Is there any other way to check if simulcast has been enabled?

**Comment by timrozum** [comment]
Hi @simbara, 

The iOS SDK does not provide a way to determine if simulcast is enabled. However you could verify that `ConnectOptions` is configured properly before connecting to a room.
