### ISSUE TITLE
Running the app and then running unit tests causes crash

### ISSUE THREAD

**Issue by timrozum** [twilio/twilio-video-app-ios#12]
Running unit tests `⌘U` will crash if the app was run `⌘R` on the device previously. To work around this delete the app and then run unit tests. 

The problem seems to be caused by `application(_:configurationForConnecting:options:)` not always getting called at launch.

**Comment by timrozum** [comment]
I have submitted feedback to Apple to learn more about this.

**Comment by aaalaniz** [comment]
Closing this issue for now. Please reference [project README](https://github.com/twilio/twilio-video-app-ios#known-issues) to workaround this issue.
