### ISSUE TITLE
What are 'Stores' and why are they used frequently in the demo application? 

### ISSUE THREAD

**Issue by shalem93** [twilio/twilio-video-app-ios#133]
for example. MainParticipantStore.swift, AuthStore.swift, DeepLinkStore.swift
I see you guys use the Factory pattern as well but I can't find info on Stores on google and am just curious why you use this design pattern.

If someone can point me to an article on this concept it would be appreciated as well :)

**Comment by paynerc** [comment]
I've moved tis issue to the [twilio-video-app-ios] repo as it is dealing with implementation details about the Video App.

**Comment by shalem93** [comment]
> Great question @shalem93!
> 
> This provides some history of the convention: https://softwareengineering.stackexchange.com/questions/184396/mvcs-model-view-controller-store
> 
> And here is an Apple API that uses `store` semantics:
> https://developer.apple.com/documentation/swiftui/appstorage
> 
> But in a nutshell a store is just an object that handles data access so that it is single responsibility and reusable. This keeps higher layers simple. For example a view model can use a store to easily read data so that the view model is really just transforming data for display in a view and not directly having to deal with all the complexities about how the data is fetched or modified.
> 
> Data that a store handles might be on the file system, remote (for example REST API), or just in memory.
> 
> These objects could also be called services or managers. The name does not matter a lot but I like how store implies data access where they are used in the demo app. And I think at least in some of the early SwiftUI examples I saw from Apple the store convention was used which was nice to see.
> 
> Let me know if that helps!

Thank you for this response! Very helpful 👍

**Comment by timrozum** [comment]
You're welcome!
