### ISSUE TITLE
when connected iOS mobile to web. video not appears

### ISSUE THREAD

**Issue by YogeshSDM** [twilio/twilio-video-app-ios#148]
I am using pod version
pod 'TwilioVideo', '3.8.0'

for single user video call everything works fine.
1. mobile to mobile- working
2. mobile to web - working

But in this tutorial when connected from
mobile to mobile - works fine
Mobile to web - video not displayed
mobile to desktop app - video not displayed.

Please let us know what we need to do to show web user video in mobile.
I am using same code used in this tutorial with access token only

Thanks.

**Comment by YogeshSDM** [comment]
Any idea about this bug. 
Please reply. we have to release our app

**Comment by timrozum** [comment]
@YogeshSDM very sorry for the much delayed response. Are you still having the issue? Are you using one of our sample apps for the web app also? If so what repo?

I suspect there may be an issue with different platforms using different track names. Please make sure mobile and web apps are using the same track name for the camera. [Here is the camera track name in this repo](https://github.com/twilio/twilio-video-app-ios/blob/d7771076e06e2d9de172a226b0d4b9bb3a07b3c9/VideoApp/VideoApp/Video/Tracks/Core/TrackName.swift#L20).

**Comment by timrozum** [comment]
I'm going to close this but feel free to respond here if there is any remaining issue.
