### ISSUE TITLE
Need help with overriding with my own twilio token.

### ISSUE THREAD

**Issue by SKS-WAR** [twilio/twilio-video-app-ios#149]
I have by passed the auth to go to the lobby. Now I need help with joining a custom room. The room is being nil perhaps and I am unable to connect to my required room.

I have hard coded the accessToken. The room is just not being set.

**Comment by SKS-WAR** [comment]
It's urgent. Please help @paynerc @kwhinnery @Gipetto @luisuribe

**Comment by paynerc** [comment]
@SKS-WAR,

Can you provide a code sample so we can get an idea of what is going on? Also any debug logs that may help us understand what you are seeing?

Ryan

**Comment by timrozum** [comment]
@SKS-WAR 

Also can you specify exactly what line of code from this repo (or sample code):

1. Where you see that room is nil?
2. Where you hard-coded the access token?

Thanks!

**Comment by SKS-WAR** [comment]
Sorry for the trouble, my access token was not exactly what it was supposed to be. Only by correcting the token everything works fine. 

**Great project guys just mention what to do when we will be integrating this into another project, going through the entire flow is troublesome and there is no walk through.** 
Much appreciated for the concern.

Thank you,

**Comment by timrozum** [comment]
@SKS-WAR I'm glad you have things working now.

And thanks for the feedback. I think it would be a valid improvement in the future to explain the architecture more at a high level and maybe provide tips for moving core pieces from this repo to a different app. Would that help address your concern?

**Comment by SKS-WAR** [comment]
@timmydoza Yes that would help a great deal.

**Comment by aaalaniz** [comment]
Hey @SKS-WAR 

We will close this issue for now as the original problem has been remediated.

Thank you for the suggestion!
