### ISSUE TITLE
WindowSceneObserving is only available in iOS 13 or newer

### ISSUE THREAD

**Issue by dsmwong** [twilio/twilio-video-app-ios#158]
#### Description

After ⌘R, getting the following errors with Video-Community scheme. 

`'WindowSceneObserving' is only available in iOS 13 or newer` in VideoStore.swift
and 
`Redundant constraint 'Self' : 'AnyObject'` in Participant.swift

#### Steps to Reproduce

1. `pod install`
1. Changed Team
1. made Bundle ID unique
1. Select Video-Community scheme and physical device
1. ⌘R

#### Versions

- Video app version: 0.1.0
- iOS version: 14.5
- Device: iPhone 12 P
- Xcode version: 12.5

**Comment by timrozum** [comment]
The PR has been merged.
