### ISSUE TITLE
In old projects using objective-c, twiliovideo.roomdelegate cannot be triggered

### ISSUE THREAD

**Issue by zhaoshichao** [twilio/twilio-video-app-ios#160]
self.twilioVideoSDKType.connect(options: options, delegate: self)   
There was no callback after that

**Comment by timrozum** [comment]
Hi @zhaoshichao, 

Could you provide some sample code so I can better understand how you're using Swift and Objective-C together? Thanks!

**Comment by timrozum** [comment]
Going to close this but feel free to reach out here again if you have more issues.
