### ISSUE TITLE
How to use project with out passcode

### ISSUE THREAD

**Issue by karthiksaral** [twilio/twilio-video-app-ios#162]
Dear team, 

Your works are valuable, here I try to customise the code with out passcode  alternatively I used fetch accessToken concept, I face some issues, for example, I called my own acesstoken API call, in here if I sent the body of params

roomName: "peer", userName: "karthik"

the params automatically converted to 

request body: {
    "room_name" = peer;
    "user_name" = karthik;
}

can you help me to resolve this issues, its really hopeful to integrate in my live project

**Comment by timrozum** [comment]
Hi @karthiksaral, 

You can fetch your access token however you want. And then when you have obtained the access token just make sure it is used [when the app uses the video SDK to connect to the room](https://github.com/twilio/twilio-video-app-ios/blob/e3bda53bcb7391dd0e0fddcd4f26c483ee4132dc/VideoApp/VideoApp/Video/Room/Room.swift#L70).

Does that help?

**Comment by karthiksaral** [comment]
@timrozum - thanks for your valuable reply, I tried the way what you given, its works fine, but unfortunately remote video is not render in local, can you help to resolve this issue. if its done I ready to move this file into live project.

web url : https://e55338bfc012.ngrok.io/quickstart/

Mobile app: https://www.sendtransfer.com/download.php?id=22e5e79fc81b6ffbf47df89116320006


Thanks and Regards
Anbu.karthik

**Comment by timrozum** [comment]
Will close this since we plan to stick to passcode auth for this repo.

**Comment by karthiksaral** [comment]
sure, thanks its useful for us.
