### ISSUE TITLE
Error view visibility when we have video track nil

### ISSUE THREAD

**Issue by MayurTanna1** [twilio/twilio-video-app-ios#173]
> #### Before Creating an Issue
>
> - If there is an issue specific to the video app report it here. If there is an issue or question related to the video SDK please [create an SDK issue](https://github.com/twilio/twilio-video-ios/issues) instead.
> - Make sure the issue is not already addressed by [docs](https://www.twilio.com/docs/video) or [existing issues](https://github.com/twilio/twilio-video-app-ios/issues).
> - Please do not share any 
[Personally Identifiable Information](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive information like API keys when creating an issue.

#### Description

we try to disable video , it doesn't show error view when video track is nil or video is disable.

#### Steps to Reproduce

1. perform  toggleVideoPressed in LobbyViewController
2. Disabling video camera makes video track nil but it doesn't show Error View when video track is nil 

#### Expected Behaviour
1. I believe we should have error view visible when we don't have video track.

#### Versions

- Video app version: 4.1.0
- iOS version: 14.6
- Device: iPhone 7
- Xcode version: 12.4

#### Log
```
// Log output when the issue occurs
```

#### Suggestion can be
- I believe we can update below lines inside VideoView.swift

From
errorView.isHidden = !(config.videoTrack?.isSwitchedOff ?? false)

To 
errorView.isHidden = !(config.videoTrack?.isSwitchedOff ?? true)

Thanks for your time :)

**Comment by timrozum** [comment]
Thanks for the feedback @MayurTanna1. As discussed in [this PR](https://github.com/twilio/twilio-video-app-ios/pull/171#issuecomment-934835596) I think the functionality is by design. Please see the PR for more details. Thanks!
