### ISSUE TITLE
TwillioVideo pod not installing

### ISSUE THREAD

**Issue by Leepian** [twilio/twilio-video-app-ios#181]
I am trying this repo on my system, when installing pods when it comes to TwilioVideo it generates error. Any idea please.

Thanks in advance

**Comment by timrozum** [comment]
Hi @Leepian, I can confirm that it is working with pod version 1.10.2. Can you try that version?

Also can you provide details about the error you are seeing? Thanks!

**Comment by Leepian** [comment]
Yes, I installed it successfully. Thanks for the reply @timrozum
