### ISSUE TITLE
Rounded VideoView

### ISSUE THREAD

**Issue by HakanSAYAR** [twilio/twilio-video-app-ios#183]
Description

Hi Devs, I'm developing a P2P&Group video call application using your SDK. I set the videoView's contentMode to `.scaleAspectFit`. But I got black lines on left and right or top and bottom depends on video frames that I get receiving. How can I get videoView filled with video feed by having the same aspect ratio or by setting the content mode on videoView?

Versions

Video app version: 3.7
iOS version: 15.2.1
Device: iPhone 7
Xcode version: 13

**Comment by timrozum** [comment]
Hi @HakanSAYAR, I think `.scaleAspectFill` should provide the behavior you need.

https://developer.apple.com/documentation/uikit/uiview/contentmode/scaleaspectfill

**Comment by timrozum** [comment]
Going to close this out but let me know if you have more questions.
