### ISSUE TITLE
After Deploying app generate error like this

### ISSUE THREAD

**Issue by JigarAdbiz** [twilio/twilio-video-app-ios#186]
> #### Before Creating an Issue
>
> - If there is an issue specific to the video app report it here. If there is an issue or question related to the video SDK please [create an SDK issue](https://github.com/twilio/twilio-video-ios/issues) instead.
> - Make sure the issue is not already addressed by [docs](https://www.twilio.com/docs/video) or [existing issues](https://github.com/twilio/twilio-video-app-ios/issues).
> - Please do not share any 
[Personally Identifiable Information](https://www.twilio.com/docs/glossary/what-is-personally-identifiable-information-pii) or sensitive information like API keys when creating an issue.

#### Description

% twilio rtc:apps:video:deploy --authentication passcode
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: "https://github.com/twilio-labs/plugin-rtc"
#### Steps to Reproduce

1. [Step one]
1. [Step two]
1. [Insert as many steps as needed]

#### Expected Behavior

[What you expect to happen]

#### Versions

- Video app version: [e.g. 0.1.0 (33)]
- iOS version: [e.g. 13.1]
- Device: [e.g. iPhone 11]
- Xcode version: [e.g. 11.3.1]

#### Log
```
// Log output when the issue occurs
```

**Comment by timrozum** [comment]
Hi @JigarAdbiz have you tried these steps? https://github.com/twilio/twilio-video-app-ios#troubleshooting

**Comment by timrozum** [comment]
Going to close this out but let me know if you have more questions.
