### ISSUE TITLE
Configuration steps for Community build missing? Secrets 

### ISSUE THREAD

**Issue by sandeep131** [twilio/twilio-video-app-ios#60]
Hi - I am trying to use this sample to build a prototype but found that the twilio-cli to receive the passcode to be used is not working.  Assuming that it is needed to resolve to an instance of the twilio server.  I don't find any instructions or placeholder to provide the account SID, token and secret.  Am I missing something?  I tried to generate a token using our server and force use it for a room "joinRoomWithAccessToken:(NSString *)accessToken", but using that token to connect to the room returns an error from SDK:

Error Domain=com.twilio.video Code=20103 "Invalid Access Token issuer/subject" UserInfo={NSLocalizedDescription=Invalid Access Token issuer/subject}

Realized that I have not set up any of our account info - What is secrets.xcconfig & do we have to do anything with the Firebase for the community project?

Thanks!

**Comment by timrozum** [comment]
Hi,

Did you run `twilio login`? That should ask for credentials. This step is on same page as Twilio CLI install instructions. I'm realizing now that it is technically separate from install so we should mention it specifically in the readme. 

https://www.twilio.com/docs/twilio-cli/quickstart#login-to-your-twilio-account

You do not need to modify secrets.xcconfig or anything related to Firebase for community build. 

Let me know if that helps.

**Comment by timrozum** [comment]
I updated the readme to explicitly include login step: https://github.com/twilio/twilio-video-app-ios/pull/61

Thanks for the feedback!

**Comment by sandeep131** [comment]
Thanks - will try shortly... Best!

**Comment by aaalaniz** [comment]
Hey @sandeep131 

Thank you for filing the issue. We have updated the README accordingly with your feedback. I'm closing this issue for now, but please re-open if you continue to have trouble getting started.

Thanks!
