### ISSUE TITLE
Cocoapods warning upon running `pod install`

### ISSUE THREAD

**Issue by davidfmiller** [twilio/twilio-video-app-ios#68]
#### Description

Running into the following problem after running `pod install`:

```shell
[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Video-Internal` to `Target Support Files/Pods-Video-Twilio-Video-Internal/Pods-Video-Twilio-Video-Internal.release.xcconfig` or include the `Target Support Files/Pods-Video-Twilio-Video-Internal/Pods-Video-Twilio-Video-Internal.release.xcconfig` in your build configuration (`IOSVideoAppSecrets/Secrets.xcconfig`).
```

#### Steps to Reproduce

1. Clone the repo
1. `cd` into the repo's folder
1. Run `pod install`
1. Observe warning/error.

#### Expected Behavior

Pods to install successfully.

#### Versions

- Video app version: 0.1.0 (33)
- Xcode version: 11.4
- iOS version: N/A
- Device: N/A

**Comment by davidfmiller** [comment]
Looks like the other `Video-Community` target can be built & run without issues, though.

**Comment by timrozum** [comment]
Sorry for the delayed response, I had an issue with my GitHub notifications.

Yes `Video-Community` is the scheme that should be used by external developers. This is documented at https://github.com/twilio/twilio-video-app-ios#run.

Let me know if there are any more issues.

**Comment by pmorgaonkar** [comment]
<img width="1727" alt="Screen Shot 2020-08-05 at 8 16 11 PM" src="https://user-images.githubusercontent.com/25557343/89486734-924f8400-d758-11ea-8e77-bef4b1bf1d26.png">

I followed the instructions as mentioned in. the Twilio channel + docs  [https://www.youtube.com/watch?v=pSASQcHrmPg](url)
Facing. the same failure  as mentioned by davidfmiller  and unable to resolve it... Please help.

**Comment by timrozum** [comment]
@pmorgaonkar I don't think the pod warnings is related to your build errors. And it looks like you have the correct `Video-Community` scheme selected. To make sure this is not an Xcode bug can you try the following?

1. Product > Clean Build Folder
1. Restart Xcode
1. Restart macOS

Please let me know if that helps!
