### ISSUE TITLE
Sign-in Error 

### ISSUE THREAD

**Issue by davidfmiller** [twilio/twilio-video-app-ios#70]
#### Description

"Sign in Error. An error occurred. Please try again." is displayed.

#### Steps to Reproduce

1. Follow setup & install steps.
1. Build & run Community target on an iOS device.
1. Enter a name & passcode generated from the CLI utility when application finishes launch on device.
1. Error dialog as described above is presented.

#### Expected Behavior

Authentication should proceed and access to the application should be granted.

#### Versions

- Video app version: 0.1.0 (33)
- iOS version: 13.4
- Device: iPhone 8
- Xcode version: 11.4

#### Log

No log output is produced.

![IMG_8597](https://user-images.githubusercontent.com/12614/78833089-8bcb1e80-79a9-11ea-98b8-443ca2b545e7.jpg)

**Comment by timrozum** [comment]
Sorry for the delayed response. I had an issue with GitHub notifications.

Something suspicious is video app version `0.1.0 (33)`. The latest version on master branch is `0.1.0 (51)`. Did you checkout current master branch? Looks like you were following instructions properly. Let me know if this helps and if you know how you got the older version.

Thanks!

**Comment by timrozum** [comment]
I'm pretty sure things will work better with latest software. If not just let me know!

**Comment by davidfmiller** [comment]
Hiya, sorry, missed this notification. I changed the application bundle identifier and things started working... mysterious.

**Comment by timrozum** [comment]
Interesting, thanks for letting me know!
