### ISSUE TITLE
How to use with the token server at twilio-video-app-react

### ISSUE THREAD

**Issue by Nicholashuber** [twilio/twilio-video-app-ios#73]
Hello I'm using the twilio-video-app-react repo and im looking to use this ios app to connect with rooms im generating on the twilio-video-app-react. How would I point the internals to reference this other token server and connect to the rooms?

**Comment by timrozum** [comment]
Yes this is supported. When you deployed the token server the CLI should have output a passcode. Enter this passcode into the iOS app when prompted at launch. Then join the same room name on iOS and web.

This is documented here:

https://github.com/twilio/twilio-video-app-ios#deploy-twilio-access-token-server
https://github.com/twilio/twilio-video-app-ios#start-video-conference

If you can't get to the passcode and need to generate a new one instructions to redeploy token server are here: 

https://github.com/twilio/twilio-video-app-ios#deploy-twilio-access-token-server

Let me know if there are any other questions!

**Comment by borgo** [comment]
Hey Tim, actually I had a similar question. I would like the iOS app to work with React app that's already running on my server. iOS (and Android) app would be using the token generation service built in the React app (https://example.com/token?identity=joe&roomName=test). I understand that using passcode is not meant for production.

What's the recommended workflow for production? Do iOS and Android demo apps work with React app as a bundle. Or do I need to have a standalone token service for the apps? Thanks

**Comment by timrozum** [comment]
Hi @borgo, this page has more information about generating access tokens: https://www.twilio.com/docs/video/tutorials/user-identity-access-tokens

It is a good idea to use a single token service that serves tokens to all clients including React, iOS, and Android. The important thing for production is to have a secure authentication method, such as Google sign in, which will be more secure than our passcode implementation. 

Does that help?

**Comment by borgo** [comment]
Thanks @timrozum, I'll try to hook up to a snadalone token service using https://github.com/TwilioDevEd/video-access-token-server-node from all three clients.
