### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by maidmehic** [twilio/twilio-video-app-ios#75]
#### Description

Hello everyone. I cloned the app succesfully but when trying to install pods with `pod install`, I'm getting next error provided below in Log section

#### Steps to Reproduce

1. Follow setup & install steps.
2. Enter `pod install` in a terminal to install required pods

#### Expected Behavior

Pods successfully installed

#### Log
<img width="930" alt="Screenshot 2020-04-27 at 15 58 30" src="https://user-images.githubusercontent.com/45770647/80380828-63478d80-88a0-11ea-9f5a-69ba37beeee0.png">

**Comment by maidmehic** [comment]
`pod repo update` fixed the issue.

**Comment by timrozum** [comment]
Great!
