### ISSUE TITLE
Empty Credentials in twilio debugger after initiating the call

### ISSUE THREAD

**Issue by yatindma** [twilio/twilio-video-app-ios#76]
While starting the call from iOS sometimes call is going and getting disconnected in 2-3 sec and the error log we are getting on twilio is "Empty Credentials"

Please help to fix this bug

**Comment by timrozum** [comment]
Hi @yatindma,

I want to make sure I understand when you are receiving this error. If this is presented in the UI could you send a screenshot? And could you provide the output of the Xcode console? Thanks!

**Comment by timrozum** [comment]
Going to close this out but if it's still a problem just let me know with a few more details and we can reopen. Thanks!
