### ISSUE TITLE
keyWindow' was deprecated in iOS 13.0

### ISSUE THREAD

**Issue by fmatosic** [twilio/twilio-video-app-ios#77]
After following the instructions cam to the Run ⌘R the appand I received an error that Alamofire(in pod file is 5.0.2) requires to be build in ios 13, so I changed the Target to ios 13 then rebuild and got:
/Users/filipmatosic/Development/ios/testing/twilio-video-app-ios-master/VideoApp/VideoApp/Video/VideoAppCameraSource.swift:65:95: 'keyWindow' was deprecated in iOS 13.0: Should not be used for applications that support multiple scenes as it returns a key window across all connected scenes

Screen shot with error added
#### Expected Behavior

[What you expect to happapplication to builden]

#### Versions

- Video app version: 0.1.0 (52)
- iOS version:  13.0]
- Device: iPhone 8+ 
- Xcode version: 11.4.1

<img width="1894" alt="Screenshot 2020-05-04 at 23 10 11" src="https://user-images.githubusercontent.com/3234580/81014441-26aa0200-8e5d-11ea-8f05-225b376f76cc.png">

**Comment by fmatosic** [comment]
Changing Alamofire to 5.0.0 and project build to ios 12.4 is a work around

**Comment by timrozum** [comment]
@fmatosic I'm not sure what caused the original Alamofire issue but I'm glad things are working for you now. The project is setup for iOS 11 deployment target and I suspect the `keyWindow` error only happens if deployment target is iOS 13. So yeah setting it to iOS 12.4 should also work.
